# Generated by Django 3.0.2 on 2020-01-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_hex',
            field=models.CharField(default='0b51a828fddf4a3cbfab', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='story_code',
            field=models.CharField(default='3297b49b33904e39b626', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='prayerrequest_hex',
            field=models.CharField(default='9e4eb17725c9404f950ea2', editable=False, max_length=22, unique=True),
        ),
    ]
