# Generated by Django 3.0.2 on 2020-02-25 11:01

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpcenter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UsersRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_hex', models.CharField(default='ad0afa25bd', editable=False, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[{'', 'Select Help Category'}, ('Account issues', 'Account issues'), ('Publishing issues', 'Publishing issues'), ('Other', 'Other')], max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelpCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_hex', models.CharField(default=helpcenter.models.MakeOTP, editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('slug', models.SlugField(default='djangodbmodelsfieldscharfield', max_length=500, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpcenter.Section')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
