# Generated by Django 3.0.2 on 2020-02-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersrequest',
            name='help_hex',
            field=models.CharField(default='1b5b8f294e', editable=False, max_length=20, unique=True),
        ),
    ]
